#default spring profile
server:
  error:
    include-message: always


logging:
  level:
    root: INFO
    com.butchery: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      username: user
      password: pwd
      host: localhost
      port: 27017
      database: purchases-db
      authentication-database: admin
      auto-index-creation: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

app:
  customers-service:
    host: localhost
    port: 7001
  meats-service:
    host: localhost
    port: 7002
  butchers-service:
    host: localhost
    port: 7003

---
spring:
  config:
    activate:
      on-profile: docker

spring.data.mongodb.host: mongodb

app:
  customers-service:
    host: customers-service
    port: 8080
  meats-service:
    host: meats-service
    port: 8080
  butchers-service:
    host: butchers-service
    port: 8080

server.port: 8080



